/**
 * Fallback transaction data for when Plaid sandbox returns no transactions
 * 
 * This addresses the common issue where Plaid sandbox accounts are empty
 * or have been reset, allowing us to still demonstrate the AI categorization
 * and budget suggestion features.
 */

export const FALLBACK_TRANSACTIONS = [
  {
    account_id: 'fallback_checking_001',
    account_owner: null,
    amount: 6.33,
    authorized_date: null,
    authorized_datetime: null,
    category: null,
    category_id: null,
    check_number: null,
    counterparties: [],
    date: '2025-07-31',
    datetime: null,
    iso_currency_code: 'USD',
    location: {
      address: null,
      city: null,
      country: null,
      lat: null,
      lon: null,
      postal_code: null,
      region: null,
      store_number: null
    },
    logo_url: null,
    merchant_entity_id: null,
    merchant_name: null,
    name: 'Uber 072515 SF**POOL**',
    payment_channel: 'other',
    payment_meta: {
      by_order_of: null,
      payee: null,
      payer: null,
      payment_method: null,
      payment_processor: null,
      ppd_id: null,
      reason: null,
      reference_number: null
    },
    pending: false,
    pending_transaction_id: null,
    personal_finance_category: { confidence_level: 'LOW', detailed: 'OTHER', primary: 'OTHER' },
    personal_finance_category_icon_url: 'https://plaid-category-icons.plaid.com/PFC_OTHER.png',
    transaction_code: null,
    transaction_id: 'fallback_uber_001',
    transaction_type: 'unresolved',
    unofficial_currency_code: null,
    website: null
  },
  {
    account_id: 'fallback_checking_001',
    account_owner: null,
    amount: 5.4,
    authorized_date: null,
    authorized_datetime: null,
    category: null,
    category_id: null,
    check_number: null,
    counterparties: [],
    date: '2025-07-18',
    datetime: null,
    iso_currency_code: 'USD',
    location: {
      address: null,
      city: null,
      country: null,
      lat: null,
      lon: null,
      postal_code: null,
      region: null,
      store_number: null
    },
    logo_url: null,
    merchant_entity_id: null,
    merchant_name: null,
    name: 'Uber 063015 SF**POOL**',
    payment_channel: 'other',
    payment_meta: {
      by_order_of: null,
      payee: null,
      payer: null,
      payment_method: null,
      payment_processor: null,
      ppd_id: null,
      reason: null,
      reference_number: null
    },
    pending: false,
    pending_transaction_id: null,
    personal_finance_category: { confidence_level: 'LOW', detailed: 'OTHER', primary: 'OTHER' },
    personal_finance_category_icon_url: 'https://plaid-category-icons.plaid.com/PFC_OTHER.png',
    transaction_code: null,
    transaction_id: 'fallback_uber_002',
    transaction_type: 'unresolved',
    unofficial_currency_code: null,
    website: null
  },
  {
    account_id: 'fallback_checking_001',
    account_owner: null,
    amount: -500,
    authorized_date: null,
    authorized_datetime: null,
    category: null,
    category_id: null,
    check_number: null,
    counterparties: [],
    date: '2025-07-16',
    datetime: null,
    iso_currency_code: 'USD',
    location: {
      address: null,
      city: null,
      country: null,
      lat: null,
      lon: null,
      postal_code: null,
      region: null,
      store_number: null
    },
    logo_url: null,
    merchant_entity_id: null,
    merchant_name: null,
    name: 'United Airlines',
    payment_channel: 'other',
    payment_meta: {
      by_order_of: null,
      payee: null,
      payer: null,
      payment_method: null,
      payment_processor: null,
      ppd_id: null,
      reason: null,
      reference_number: null
    },
    pending: false,
    pending_transaction_id: null,
    personal_finance_category: {
      confidence_level: 'LOW',
      detailed: 'TRAVEL_FLIGHTS',
      primary: 'TRAVEL'
    },
    personal_finance_category_icon_url: 'https://plaid-category-icons.plaid.com/PFC_TRAVEL.png',
    transaction_code: null,
    transaction_id: 'fallback_united_001',
    transaction_type: 'special',
    unofficial_currency_code: null,
    website: null
  },
  {
    account_id: 'fallback_checking_001',
    account_owner: null,
    amount: 12,
    authorized_date: null,
    authorized_datetime: null,
    category: null,
    category_id: null,
    check_number: null,
    counterparties: [],
    date: '2025-07-15',
    datetime: null,
    iso_currency_code: 'USD',
    location: {
      address: null,
      city: null,
      country: null,
      lat: null,
      lon: null,
      postal_code: null,
      region: null,
      store_number: null
    },
    logo_url: null,
    merchant_entity_id: null,
    merchant_name: null,
    name: "McDonald's",
    payment_channel: 'other',
    payment_meta: {
      by_order_of: null,
      payee: null,
      payer: null,
      payment_method: null,
      payment_processor: null,
      ppd_id: null,
      reason: null,
      reference_number: null
    },
    pending: false,
    pending_transaction_id: null,
    personal_finance_category: {
      confidence_level: 'LOW',
      detailed: 'FOOD_AND_DRINK_FAST_FOOD',
      primary: 'FOOD_AND_DRINK'
    },
    personal_finance_category_icon_url: 'https://plaid-category-icons.plaid.com/PFC_FOOD_AND_DRINK.png',
    transaction_code: null,
    transaction_id: 'fallback_mcdonalds_001',
    transaction_type: 'place',
    unofficial_currency_code: null,
    website: null
  },
  {
    account_id: 'fallback_checking_001',
    account_owner: null,
    amount: 4.33,
    authorized_date: null,
    authorized_datetime: null,
    category: null,
    category_id: null,
    check_number: null,
    counterparties: [],
    date: '2025-07-15',
    datetime: null,
    iso_currency_code: 'USD',
    location: {
      address: null,
      city: null,
      country: null,
      lat: null,
      lon: null,
      postal_code: null,
      region: null,
      store_number: null
    },
    logo_url: null,
    merchant_entity_id: null,
    merchant_name: null,
    name: 'Starbucks',
    payment_channel: 'other',
    payment_meta: {
      by_order_of: null,
      payee: null,
      payer: null,
      payment_method: null,
      payment_processor: null,
      ppd_id: null,
      reason: null,
      reference_number: null
    },
    pending: false,
    pending_transaction_id: null,
    personal_finance_category: {
      confidence_level: 'LOW',
      detailed: 'FOOD_AND_DRINK_COFFEE',
      primary: 'FOOD_AND_DRINK'
    },
    personal_finance_category_icon_url: 'https://plaid-category-icons.plaid.com/PFC_FOOD_AND_DRINK.png',
    transaction_code: null,
    transaction_id: 'fallback_starbucks_001',
    transaction_type: 'place',
    unofficial_currency_code: null,
    website: null
  },
  {
    account_id: 'fallback_checking_001',
    account_owner: null,
    amount: 89.4,
    authorized_date: null,
    authorized_datetime: null,
    category: null,
    category_id: null,
    check_number: null,
    counterparties: [],
    date: '2025-07-14',
    datetime: null,
    iso_currency_code: 'USD',
    location: {
      address: null,
      city: null,
      country: null,
      lat: null,
      lon: null,
      postal_code: null,
      region: null,
      store_number: null
    },
    logo_url: null,
    merchant_entity_id: null,
    merchant_name: null,
    name: 'SparkFun',
    payment_channel: 'other',
    payment_meta: {
      by_order_of: null,
      payee: null,
      payer: null,
      payment_method: null,
      payment_processor: null,
      ppd_id: null,
      reason: null,
      reference_number: null
    },
    pending: false,
    pending_transaction_id: null,
    personal_finance_category: { confidence_level: 'LOW', detailed: 'OTHER', primary: 'OTHER' },
    personal_finance_category_icon_url: 'https://plaid-category-icons.plaid.com/PFC_OTHER.png',
    transaction_code: null,
    transaction_id: 'fallback_sparkfun_001',
    transaction_type: 'unresolved',
    unofficial_currency_code: null,
    website: null
  },
  {
    account_id: 'fallback_savings_001',
    account_owner: null,
    amount: 25,
    authorized_date: null,
    authorized_datetime: null,
    category: null,
    category_id: null,
    check_number: null,
    counterparties: [],
    date: '2025-07-18',
    datetime: null,
    iso_currency_code: 'USD',
    location: {
      address: null,
      city: null,
      country: null,
      lat: null,
      lon: null,
      postal_code: null,
      region: null,
      store_number: null
    },
    logo_url: null,
    merchant_entity_id: null,
    merchant_name: null,
    name: 'CREDIT CARD 3333 PAYMENT *//',
    payment_channel: 'other',
    payment_meta: {
      by_order_of: null,
      payee: null,
      payer: null,
      payment_method: null,
      payment_processor: null,
      ppd_id: null,
      reason: null,
      reference_number: null
    },
    pending: false,
    pending_transaction_id: null,
    personal_finance_category: {
      confidence_level: 'LOW',
      detailed: 'LOAN_PAYMENTS_CREDIT_CARD_PAYMENT',
      primary: 'LOAN_PAYMENTS'
    },
    personal_finance_category_icon_url: 'https://plaid-category-icons.plaid.com/PFC_LOAN_PAYMENTS.png',
    transaction_code: null,
    transaction_id: 'fallback_cc_payment_001',
    transaction_type: 'special',
    unofficial_currency_code: null,
    website: null
  },
  {
    account_id: 'fallback_savings_001',
    account_owner: null,
    amount: -4.22,
    authorized_date: null,
    authorized_datetime: null,
    category: null,
    category_id: null,
    check_number: null,
    counterparties: [],
    date: '2025-07-13',
    datetime: null,
    iso_currency_code: 'USD',
    location: {
      address: null,
      city: null,
      country: null,
      lat: null,
      lon: null,
      postal_code: null,
      region: null,
      store_number: null
    },
    logo_url: null,
    merchant_entity_id: null,
    merchant_name: null,
    name: 'INTRST PYMNT',
    payment_channel: 'other',
    payment_meta: {
      by_order_of: null,
      payee: null,
      payer: null,
      payment_method: null,
      payment_processor: null,
      ppd_id: null,
      reason: null,
      reference_number: null
    },
    pending: false,
    pending_transaction_id: null,
    personal_finance_category: { confidence_level: 'LOW', detailed: 'OTHER', primary: 'OTHER' },
    personal_finance_category_icon_url: 'https://plaid-category-icons.plaid.com/PFC_OTHER.png',
    transaction_code: null,
    transaction_id: 'fallback_interest_001',
    transaction_type: 'unresolved',
    unofficial_currency_code: null,
    website: null
  },
  {
    account_id: 'fallback_savings_001',
    account_owner: null,
    amount: 5850,
    authorized_date: null,
    authorized_datetime: null,
    category: null,
    category_id: null,
    check_number: null,
    counterparties: [],
    date: '2025-07-17',
    datetime: null,
    iso_currency_code: 'USD',
    location: {
      address: null,
      city: null,
      country: null,
      lat: null,
      lon: null,
      postal_code: null,
      region: null,
      store_number: null
    },
    logo_url: null,
    merchant_entity_id: null,
    merchant_name: null,
    name: 'ACH Electronic CreditGUSTO PAY 123456',
    payment_channel: 'other',
    payment_meta: {
      by_order_of: null,
      payee: null,
      payer: null,
      payment_method: 'ACH',
      payment_processor: null,
      ppd_id: null,
      reason: null,
      reference_number: null
    },
    pending: false,
    pending_transaction_id: null,
    personal_finance_category: { confidence_level: 'MEDIUM', detailed: 'INCOME_SALARY', primary: 'INCOME' },
    personal_finance_category_icon_url: 'https://plaid-category-icons.plaid.com/PFC_INCOME.png',
    transaction_code: null,
    transaction_id: 'fallback_salary_001',
    transaction_type: 'special',
    unofficial_currency_code: null,
    website: null
  },
  {
    account_id: 'fallback_checking_001',
    account_owner: null,
    amount: 78.5,
    authorized_date: null,
    authorized_datetime: null,
    category: null,
    category_id: null,
    check_number: null,
    counterparties: [],
    date: '2025-07-16',
    datetime: null,
    iso_currency_code: 'USD',
    location: {
      address: null,
      city: null,
      country: null,
      lat: null,
      lon: null,
      postal_code: null,
      region: null,
      store_number: null
    },
    logo_url: null,
    merchant_entity_id: null,
    merchant_name: null,
    name: 'Touchstone Climbing',
    payment_channel: 'other',
    payment_meta: {
      by_order_of: null,
      payee: null,
      payer: null,
      payment_method: null,
      payment_processor: null,
      ppd_id: null,
      reason: null,
      reference_number: null
    },
    pending: false,
    pending_transaction_id: null,
    personal_finance_category: { confidence_level: 'MEDIUM', detailed: 'ENTERTAINMENT_GYMS_FITNESS', primary: 'ENTERTAINMENT' },
    personal_finance_category_icon_url: 'https://plaid-category-icons.plaid.com/PFC_ENTERTAINMENT.png',
    transaction_code: null,
    transaction_id: 'fallback_climbing_001',
    transaction_type: 'place',
    unofficial_currency_code: null,
    website: null
  }
];

/**
 * Convert fallback data to sync-like format for compatibility
 */
export function getFallbackTransactionData() {
  console.log(`🔄 [Fallback] Using ${FALLBACK_TRANSACTIONS.length} fallback transactions for demo purposes`);
  
  return {
    added: FALLBACK_TRANSACTIONS,
    modified: [],
    removed: [],
    has_more: false,
    next_cursor: 'fallback_complete'
  };
}

/**
 * Check if we should use fallback data (when Plaid sandbox is empty)
 */
export function shouldUseFallbackData(plaidResponse: any): boolean {
  const isEmpty = !plaidResponse.added || plaidResponse.added.length === 0;
  const isInitialSync = !plaidResponse.next_cursor || plaidResponse.next_cursor === null;
  
  return isEmpty && isInitialSync;
}